# Generated by Django 5.1 on 2024-09-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="orifin",
            new_name="origin",
        ),
    ]
