# Generated by Django 5.1 on 2024-12-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_number", models.CharField(max_length=20, unique=True)),
                ("requested_by", models.CharField(max_length=10)),
                ("request_type", models.CharField(max_length=100)),
                ("request_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("description", models.TextField()),
                ("reason_for_action", models.TextField()),
                (
                    "status",
                    models.CharField(blank=True, default="Unprocessed", max_length=50),
                ),
                ("assigned", models.CharField(blank=True, max_length=100, null=True)),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
