# Generated by Django 5.1 on 2024-12-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="description_of_action",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="validation_of_action",
            field=models.TextField(blank=True, null=True),
        ),
    ]
