# Generated by Django 5.1 on 2024-12-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0003_alter_request_assigned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="assigned",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
