# Generated by Django 5.1 on 2025-01-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0005_alter_request_assigned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="request_number",
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
