# Generated by Django 5.1 on 2025-01-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0006_alter_request_request_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="request_number",
            field=models.IntegerField(unique=True),
        ),
    ]
