# Generated by Django 5.1 on 2025-01-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0007_alter_request_request_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
