# Generated by Django 5.1 on 2025-01-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0008_request_attachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="attachment",
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="eco_requests.request",
                    ),
                ),
            ],
        ),
    ]
