# Generated by Django 5.1 on 2025-01-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0010_drawing_directorapproval_drawingreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="directorapproval",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="director_approvals/"
            ),
        ),
    ]
