# Generated by Django 5.1 on 2025-01-03 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0011_directorapproval_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="drawing",
            old_name="comments",
            new_name="drawing_comments",
        ),
        migrations.RenameField(
            model_name="drawingreview",
            old_name="comments",
            new_name="review_comments",
        ),
        migrations.RemoveField(
            model_name="drawing",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="drawingreview",
            name="status",
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Pending", "Pending"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director_approvals",
                        to="eco_requests.drawing",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DirectorApproval",
        ),
    ]
