# Generated by Django 5.1 on 2025-01-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0012_rename_comments_drawing_drawing_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="drawing_number",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AddField(
            model_name="drawing",
            name="drawing_revision",
            field=models.CharField(default="0", max_length=5),
        ),
    ]
