# Generated by Django 5.1 on 2025-01-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0014_rename_status_drawing_drawing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="drawing_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Obsolete", "Obsolete"),
                    ("Pending", "Pending"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
    ]
