# Generated by Django 5.1 on 2025-01-03 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0015_alter_drawing_drawing_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="approval_person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_person",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="drawing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawing_approval",
                to="eco_requests.drawing",
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="drawing_status",
            field=models.CharField(
                choices=[
                    ("Rejected", "Rejected"),
                    ("Active", "Active"),
                    ("Obsolete", "Obsolete"),
                    ("Pending", "Pending"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawing_request",
                to="eco_requests.request",
            ),
        ),
        migrations.AlterField(
            model_name="drawingreview",
            name="drawing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawing_review_drawing",
                to="eco_requests.drawing",
            ),
        ),
        migrations.AlterField(
            model_name="drawingreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewer_review",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
