# Generated by Django 5.1 on 2025-01-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0016_alter_approval_approval_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="drawing_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Rejected", "Rejected"),
                    ("Obsolete", "Obsolete"),
                    ("Pending", "Pending"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
    ]
