# Generated by Django 5.1 on 2025-01-05 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0018_alter_drawingreview_reviewer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="review_attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="eco_requests.drawingreview",
                    ),
                ),
            ],
        ),
    ]
