# Generated by Django 5.1 on 2025-01-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0019_reviewattachment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReviewAttachment",
        ),
    ]
