# Generated by Django 5.1 on 2025-01-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0020_delete_reviewattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
