# Generated by Django 5.1 on 2025-01-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0021_drawing_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawingreview",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
