# Generated by Django 5.1 on 2025-01-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0022_drawingreview_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="dir_eng",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="approval",
            name="dir_qc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="approval",
            name="originator",
            field=models.BooleanField(default=False),
        ),
    ]
