# Generated by Django 5.1 on 2025-01-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0023_approval_dir_eng_approval_dir_qc_approval_originator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawingreview",
            name="review_status",
        ),
        migrations.AddField(
            model_name="approval",
            name="reviwer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="drawing_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Rejected", "Rejected"),
                    ("Obsolete", "Obsolete"),
                    ("Submitted for Review", "Submitted for Review"),
                    ("Approval Pending", "Approval Pending"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
    ]
