# Generated by Django 5.1 on 2025-01-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0025_drawing_drawing_reviewer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="approval",
            old_name="reviwer",
            new_name="reviewer",
        ),
    ]
