# Generated by Django 5.1 on 2025-01-09 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0026_rename_reviwer_approval_reviewer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="drawing_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Rejected", "Rejected"),
                    ("Obsolete", "Obsolete"),
                    ("Subm. for Review", "Subm. for Review"),
                    ("Approval Pending", "Approval Pending"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="originator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
