# Generated by Django 5.1 on 2025-01-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0027_alter_drawing_drawing_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="requested_by",
            field=models.CharField(max_length=10),
        ),
    ]
