# Generated by Django 5.1 on 2025-01-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eco_requests", "0029_alter_request_requested_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="requested_by",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
