# Generated by Django 5.1 on 2024-09-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auction_listing_bid_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction_listing",
            name="created",
        ),
        migrations.RemoveField(
            model_name="auction_listing",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="auction_listing",
            name="description",
        ),
        migrations.RemoveField(
            model_name="auction_listing",
            name="image",
        ),
        migrations.RemoveField(
            model_name="auction_listing",
            name="is_active",
        ),
    ]
