# Generated by Django 5.1 on 2024-09-19 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_remove_auction_listing_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listing",
            name="category",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="auction_listing",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 19, 15, 35, 46, 922866)
            ),
        ),
        migrations.AddField(
            model_name="auction_listing",
            name="current_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name="auction_listing",
            name="description",
            field=models.TextField(default="No description available"),
        ),
        migrations.AddField(
            model_name="auction_listing",
            name="image",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="auction_listing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
