# Generated by Django 5.1 on 2024-09-21 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_auction_listing_category_auction_listing_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_Name", models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name="auction_listing",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 21, 15, 3, 39, 731993)
            ),
        ),
    ]
