# Generated by Django 5.1 on 2024-09-21 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auctions",
            "0006_auction_listing_owner_alter_auction_listing_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listing",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 21, 15, 14, 40, 182509)
            ),
        ),
    ]
