# Generated by Django 5.1 on 2024-09-28 14:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auctions",
            "0009_alter_auction_listing_created_alter_comment_auction_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listing",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 28, 14, 37, 4, 565445)
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="auction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auction_bid",
                to="auctions.auction_listing",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_bid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
