# Generated by Django 5.1 on 2024-09-28 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_auction_listing_created_alter_bid_auction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listing",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 28, 14, 56, 39, 634229)
            ),
        ),
    ]
